# Configuration for Rasa NLU.
language: en
pipeline: "pretrained_embeddings_spacy"


# Configuration for Rasa Core.
policies:
  - name: "FallbackPolicy"
    nlu_threshold: 0.25
    core_threshold: 0.25
    fallback_action_name: "action_fallback"

  - name: KerasPolicy
    epochs: 250
    max_history: 3
  - name: MemoizationPolicy
    max_history: 3

  - name: MappingPolicy
  - name: "FormPolicy"
