language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_crf"

policies:
  - name: "FallbackPolicy"
    nlu_threshold: 0.23
    core_threshold: 0.23
    fallback_action_name: "action_fallback"

  - name: KerasPolicy
    epochs: 250
    max_history: 3
  - name: MemoizationPolicy
    max_history: 3

  - name: "FormPolicy"
